# Generated by Django 3.2.9 on 2021-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.CharField(choices=[('Beginner ', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
