# Generated by Django 3.2.9 on 2021-11-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
